// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glqyolncdcylutzklgtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdscXlvbG5jZGN5bHV0emtsZ3RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzU3NjUsImV4cCI6MjA2MDIxMTc2NX0.5-eS9n0TWNerFhQlyVbKmAi5eGvcxBvJDxvhyRB6nrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);